### ISSUE TITLE
requirements.txt not updated

### ISSUE THREAD

**Issue by lfnetoCSW** [cslab/pyoslc#33]
Hi,
Could you please do a pip freeze to update the required packages? 

I'm using py 2.7.18 and I am not able to get flask running with the following:
aniso8601==9.0.1
attrs==21.4.0
click==7.1.2
configparser==4.0.2
contextlib2==0.6.0.post1
Flask==1.1.4
flask-restx==1.1.0
Flask-WTF==0.14.3
functools32==3.2.3.post2
importlib-metadata==2.1.3
itsdangerous==1.1.0
Jinja2==2.11.3
jsonschema==3.2.0
MarkupSafe==1.1.1
pathlib2==2.3.7.post1
pyrsistent==0.16.1
python-dotenv==0.18.0
pytz==2023.3
scandir==1.10.0
six==1.16.0
typing==3.10.0.0
urllib3==1.25.11
Werkzeug==1.0.1
WTForms==2.3.3
zipp==1.2.0

**Comment by isccarrasco** [comment]
Hi @lfnetoCSW, thanks for reporting.

I just reviewed this issue, sorry about this, it is because the newer version of `flask-restx` library is issue a new version or url lib parser, I have updated the `requirement.txt` to install the required version, the commit 20180ba solves the issue.

In the other hand, I would like to mention that as the README says, the project is being improved but is still under development, in the (develop)[https://github.com/cslab/pyoslc/tree/develop] branch you could find some new features.
